title = 'Under7kg'
baseURL = 'https://under7kg.github.io/'

languageCode = 'en-us'
theme = 'default'


# Enables Chroma-based syntax highlighting with theme "friendly"
# See https://xyproto.github.io/splash/docs/ for other theme options
pygmentsStyle = "friendly"

# If true, Chroma will highlight GitHub-style code fences in addition to
# highlight shortcodes
pygmentsCodeFences = true

[params]
  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "jin"
  github = "under7kg"
  email = "under7kg@pm.me"
  #gaid = "Your Google Analytics ID"
  bluesky = "ukigumo.bsky.social"
  nostr = "npub1c0pw59sdy4euuy7ghaxtkm73ug6gm8puhjw3fy4wtes6caxt8zasufn4de"
  #zap = "ukigumo@getalby.com"



# If not set, it will not appear. Otherwise it will show below your footer links
#copyright = "(c) 2024 Jin"